### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by violaso** [INDAPlus21/murnion-haskell-task-2#1]
**Very well done Felix!**

**_Komplettering_**: 
1) Where is your screenshot?
2) `consonant = "aeiou"` is not complete.
3) Your solution has to be case sensitive; `alphabet = "abcdefghijklmnopqrstuvwxyz"`.

I like your implementation of `fib` and `rovarsprak`!

Here are some notes on your code:

#### Kårpsravör
Sorry, but it hurts my eyes. Using list constructors `(:)` are faster than concatination `(++)`. Haskell lists are implemented as monodirectional linked lists, hence a concatination operation is linear. In comparison, the list constructor operation is constant
_Your code_:
```hs
karpsravor :: [Char] -> [Char]
-- ...
karpsravor x = if isConsonant (head x) then [head x] ++ karpsravor (drop 2 (tail x)) else [head x] ++ karpsravor(tail x)
```
_With additional pattern matching_:
```hs
karpsravor :: [Char] -> [Char]
-- ...
karpsravor (x:xs) 
  | isConsonant x = x : karpsravor $ drop 2 xs
  | otherwise = x : karpsravor xs
```

#### Medellängd
To prevent bloated API:s, help functions should be made private by example declaring them as nested.
_Your code_:
```hs
medellangd :: [Char] -> Double
medellangd "" = 0
medellangd x = (fromIntegral (length (filter isAlpha x))) / (fromIntegral (length (filter (not . isEmpty) (split x))))

isEmpty :: String -> Bool
isEmpty "" = True
isEmpty x = False

split :: String -> [String]
split [] = [""]
split (c:cs) | (not . isAlpha) c = "" : rest
             | otherwise = (c : head rest) : tail rest
    where rest = split cs
```
_With additional pattern matching_:
```hs
medellangd :: [Char] -> Double
medellangd "" = 0
medellangd x = 
  (fromIntegral $ length $ filter isAlpha x) / (fromIntegral $ length $ filter (/= "") $ split x)
  where
    split [] = [""]
    split (c:cs) 
      | (not $ isAlpha c) = "" : split cs
      | otherwise = 
          let rest = split cs
          in (c : head rest) : tail rest
```

#### Skyffla
Even here you could make use of some good ol' pattern matching.
_Your code_:
```hs
varannan :: [x] -> [x]
varannan [] = []
varannan (x:xs) = if (length xs == 0) then [x] else [x] ++ varannan (tail xs)

notVarannan :: [x] -> [x]
notVarannan [] = []
notVarannan (x:xs) = if (length xs == 0) then [] else [head xs] ++ notVarannan (tail xs)

skyffla :: [x] -> [x]
skyffla [] = []
skyffla [x] = [x]
skyffla x = varannan x ++ skyffla (notVarannan x)
```
_With additional pattern matching_:
```hs
skyffla :: [x] -> [x]
skyffla [] = []
skyffla [x] = [x]
skyffla x = varannan x ++ (skyffla $ varannan $ tail x) where
  varannan [] = []
  varannan [x] = [x]
  varannan (x:_:xs) = x : varannan xs
```

**Comment by abdbla** [comment]
That's embarrassing. Seems I forgot to update my repo from when I actually finished the kattis assignments.
Screenshot and updated code now included, I'm a little unsure what you mean by "Your solution has to be case sensitive"? I think the "alphabet" variable is a vestigial part of the code, since I'm just using the built-in function isAlpha.

Given, it's been almost 4 months since I last actually interacted with the code, so I might be missing something.

Also, a little mercy on the code please! I completely missed that there was a "learn you a haskell" book to read, so it's cobbled together from just googling.

**Comment by violaso** [comment]
Hihi, sorriiiii. My notes may sound harsh, but are meant as constructive advice. Thanks for your screenshot!
